- name: Datastax Cassandra repository
  yum_repository:
    name: datastax
    description: DataStax Repo for Apache Cassandra
    file: datastax
    baseurl: http://rpm.datastax.com/community
    gpgcheck: 0
    enabled: yes

- name: Install Cassandra required packages
  yum:
    name:
      - dsc30
      - jdk
    state: present

- name: Applying Cassandra configuration template
  template:
    src: cassandra.yaml.j2
    dest: /etc/cassandra/default.conf/cassandra.yaml
  notify: restart cassandra

- name: Start Cassandra service
  service:
    name: cassandra
    state: started
    enabled: yes
